config/routes.rb
Studyinturn2::Application.routes.draw do
  
  get "launch_page/company"
  get "launch_page/com_complete"
  get "launch_page/user"
  devise_for :companies, :controllers => {
    :registrations => 'companies/registrations'
  }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :entries do
    resource :applicants
  end

  namespace :company do
    resources :entries do
      resources :applicants, :only => ['index', 'show']
      get "mail_send" => 'applicants#mail_send'
    end
  end
  

  root 'launch_page#company'#'entries#index'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  belongs_to :user
  belongs_to :entry
end

app/controllers/applicants_controller.rb
# -*- coding: utf-8 -*-
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update, :destroy]

  # GET /applicants
  # GET /applicants.json
  def index
    # @applicants = Applicant.all
    @entries = Entry.all
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Entry.find(params[:entry_id]).applicant.new
    @applicant.user = current_user
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to entries_path, notice: '申し込み完了' }
        format.json { render action: 'show', status: :created, location: @applicant }
      else
        format.html { render action: 'new' }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to entries_path}# @applicant, notice: 'Applicant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant.destroy
    respond_to do |format|
      format.html { redirect_to applicants_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @entry = Entry.find(params[:id])
    #  @applicant = Applicant.find(params[id])# @entry.Applicant.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:user_id, :entry_id, :body)
    end
end

app/controllers/company/applicants_controller.rb
# -*- coding: utf-8 -*-
class Company::ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show]
  def index
    @applicants = Applicant.find_all_by_entry_id(params[:entry_id])
   # @applicant_user = User.find(@applicant.user_id)
  end

  def show
  end

  def mail_send

    applicant = Applicant.find(params[:entry_id])
    user = User.find(applicant.user_id)
    NoticeMail.sendmail_notification(user.email, user.name).deliver
    redirect_to company_entries_path, :notice => "メール送信完了"
    
  end

  private
  def set_applicant
    @applicant = Applicant.find(params[:id])
    @entry = Entry.find(params[:entry_id])
  end

  # def applicant_params
  #   params.require(:applicant).permit(:body)
  # end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/company/applicants_helper.rb
module Company::ApplicantsHelper
end

app/views/applicants/_form.html.erb
<%= form_for([@entry, @applicant], :url => entry_applicants_path) do |f| %>
  <% if @applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @applicant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :entry_id %><br>
    <%= f.text_field :entry_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<h1>Listing applicants</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Entry</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title %></td>
        <td><%= entry.body %></td>
        <td><%= link_to 'Show', applicant(entry) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render 'form' %>

<%#= link_to 'Back', entry_applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @applicant.user %>
</p>

<p>
  <strong>Entry:</strong>
  <%= @applicant.entry %>
</p>

<p>
  <strong>Body:</strong>
  <%= @applicant.body %>
</p>

<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>