config/routes.rb
Studyinturn2::Application.routes.draw do
  
  get "launch_page/company"
  get "launch_page/com_complete"
  get "launch_page/user"
  devise_for :companies, :controllers => {
    :registrations => 'companies/registrations'
  }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :entries do
    resource :applicants
  end

  namespace :company do
    resources :entries do
      resources :applicants, :only => ['index', 'show']
      get "mail_send" => 'applicants#mail_send'
    end
  end
  

  root 'launch_page#company'#'entries#index'

end

app/models/company.rb
# -*- coding: utf-8 -*-
class Company < ActiveRecord::Base

  has_many :entries
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :authentication_keys => [ :name]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #入力値の検証(validate)
  validates :name,
    :presence => true,
    :length   => { :maximum => 32 }
  validates :name_a,
    :presence => true,
    :length   => { :maximum => 32 }
  validates :top,
    :presence => true,
    :length   => { :maximum => 32 }
  validates :tantou,
    :presence => true,
    :length   => { :maximum => 32 }
  validates :tantou_a,
    :presence => true,
    :length   => { :maximum => 32 }
  validates :address1,
    :presence => true
  validates :address2,
    :presence => true
  validates :address3,
    :presence => true
  validates :tel,
    :presence => true
  validates :url,
    :presence => true
  validates :agreement,
    :acceptance => true
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :company
  has_many :applicant
  #belongs_to :Applicant
end

app/controllers/companies/.#registrations_controller.rb
genki@genki.local.30215

app/controllers/companies/registrations_controller.rb
# -*- coding: utf-8 -*-
class Companies::RegistrationsController < Devise::RegistrationsController

  before_filter :configure_permitted_parameters

  
  def new

    super
 
  end

  def create
    super
  end

  #strong parameterの許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) do |com|
      com.permit(:name, :name_a, :top, :tantou, :tantou_a, :email, :address1, :address2, :address3, :tel, :url, :bikou, :password, :password_confirmation)
    end
  end
end

app/controllers/companies/sessions_controller.rb
class Companies::SessionsController < Devise::SessionsController
  def new
    super
  end

  def create
    super
  end
end

app/controllers/company/applicants_controller.rb
# -*- coding: utf-8 -*-
class Company::ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show]
  def index
    @applicants = Applicant.find_all_by_entry_id(params[:entry_id])
   # @applicant_user = User.find(@applicant.user_id)
  end

  def show
  end

  def mail_send

    applicant = Applicant.find(params[:entry_id])
    user = User.find(applicant.user_id)
    NoticeMail.sendmail_notification(user.email, user.name).deliver
    redirect_to company_entries_path, :notice => "メール送信完了"
    
  end

  private
  def set_applicant
    @applicant = Applicant.find(params[:id])
    @entry = Entry.find(params[:entry_id])
  end

  # def applicant_params
  #   params.require(:applicant).permit(:body)
  # end
end

app/controllers/company/entries_controller.rb
# -*- coding: utf-8 -*-
class Company::EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_company!
  
  def index
    @entries = Entry.find_all_by_company_id([current_company])
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)
    @entry.company = current_company

    respond_to do |format|
      if @entry.save
        format.html { redirect_to company_entries_path, notice: '登録完了' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to company_entries_path}# @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # # DELETE /entries/1
  # # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to company_entries_url }
      format.json { head :no_content }
    end
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    params.require(:entry).permit(:title, :body)
  end  
end

app/controllers/entries_controller.rb
# -*- coding: utf-8 -*-
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_company!, :except => [:index, :show]

  # GET /entries
  # GET /entries.json
   def index
     @entries = Entry.all
    
   end

  # # GET /entries/1
  # # GET /entries/1.json
   def show
   #  @user_applicants = Applicant.find_all_by_user_id(current_user)
   end

   

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:title, :body)
    end
end

app/helpers/company/applicants_helper.rb
module Company::ApplicantsHelper
end

app/helpers/company/entries_helper.rb
module Company::EntriesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/company/entries/_form.html.erb
<%= form_for [:company, @entry] do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/company/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', company_entries_path %>

app/views/company/entries/index.html.erb
<%= render "layouts/header" %>

<h1>自社の求人一覧</h1>
<table>
  <thead>
    <tr>
      <th>概要(申し込み人数)</th>
      <th>仕事の内容</th>
      <th>申し込み人数</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.title.to_s + "(" + entry.applicant.count.to_s + ")" %></td>
        <td><%= entry.body %></td>
	<td><%= link_to "応募者詳細", company_entry_applicants_path(entry) %></td>
        <td>
	  <%= link_to '求人詳細', company_entry_path(entry) %></td>
        <td><%= link_to '編集', edit_company_entry_path(entry) %></td>
        <td><%= link_to '削除', company_entry_path(entry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<!-- 企業のみ案件の追加できる -->
<% if company_signed_in? -%>
  <%= link_to '案件登録', new_company_entry_path %>
<% end -%>

app/views/company/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', company_entries_path %>

app/views/company/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>概要:</strong>
  <%= @entry.title %>
</p>

<p>
  <strong>仕事の内容:</strong>
  <%= @entry.body %>
</p>

<p>
</p>
<% if company_signed_in? -%>

  <%= link_to '編集', edit_company_entry_path(@entry) %> |
<% end -%>

<%= link_to '戻る', company_entries_path %>