config/routes.rb
Studyinturn2::Application.routes.draw do
  
  get "launch_page/company"
  get "launch_page/com_complete"
  get "launch_page/user"
  devise_for :companies, :controllers => {
    :registrations => 'companies/registrations'
  }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :entries do
    resource :applicants
  end

  namespace :company do
    resources :entries do
      resources :applicants, :only => ['index', 'show']
      get "mail_send" => 'applicants#mail_send'
    end
  end
  

  root 'launch_page#company'#'entries#index'

end

app/controllers/launch_page_controller.rb
# -*- coding: utf-8 -*-
class LaunchPageController < ApplicationController
  def company
  end

  def com_complete
    # セッション無効にしたい
    NoticeMail.sendmail_notification(current_company.email, current_company.name).deliver
  end

  def user
  end

end

app/helpers/launch_page_helper.rb
module LaunchPageHelper
end

app/views/launch_page/_header.html.erb
<% if company_signed_in? -%>
  <%= link_to image_tag("logo.png"), company_entries_path(current_company) %>
<% else -%>
  <%= link_to image_tag("logo.png"), root_path %>
<% end -%>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p>
  <div Align="right">
    <% if company_signed_in? -%>
      <%= link_to "企業ログアウト", destroy_company_session_path, :method => :delete %>
    <% else -%>
      <% unless user_signed_in? -%>
	<%= link_to "企業の方　ログイン ", new_company_session_path %>
      <% end -%>

    <% end -%>
  </div>
</p>
<p>
  <div Align="center">
    <% if user_signed_in? -%>
      <%= link_to "ユーザーログアウト", destroy_user_session_path, :method => :delete %>
    <% else -%>
      <% unless company_signed_in? -%>
	<%= link_to "sign in with facebook ", user_omniauth_authorize_path(:facebook) %>

      <% end -%>
    <% end -%>





  </div>
</p>

app/views/launch_page/com_complete.html.erb
<%= link_to image_tag("logo.png"), destroy_company_session_path, :method => :delete  %>

<p>スタディインターンのお申込みが完了しました。</p>
<p>お申込みどうもありがとうございました。お申込みの確認メールを担当者のメールアドレスに送信いたしました</p>
<%= link_to "topに戻る", destroy_company_session_path, :method => :delete  %>

app/views/launch_page/company.html.erb
<div class="header">

  <div class="main_logo">
      <%= link_to image_tag("logo.png"), root_path, :class => "logo" %>
  </div>
  <div class="header-right">
    <%= link_to "既に会員登録済みの企業の方", new_company_session_path %>
  </div>
</div>

<%= image_tag("top1.png") %>
<%= link_to image_tag("link_btn.png", :class => "signup_btn"), new_company_registration_path %>  
<%= image_tag("top2.png") %>
<%= link_to image_tag("link_btn.png", :class => "signup_btn"), new_company_registration_path %>  
<%= image_tag("top3.png") %>

<!-- カウントダウン -->
<div class="Timer">
  <p class="Timer_string">キャンペーン終了まで</p>
  <div id="CDT">  </div>
</div>
<%= link_to image_tag("link_btn.png", :class => "signup_btn"), new_company_registration_path %>  

app/views/launch_page/user.html.erb
ff<h1>LaunchPage#user</h1>
<p>Find me in app/views/launch_page/user.html.erb</p>