config/routes.rb
Studyinturn2::Application.routes.draw do
  
  get "launch_page/company"
  get "launch_page/com_complete"
  get "launch_page/user"
  devise_for :companies, :controllers => {
    :registrations => 'companies/registrations'
  }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}

  resources :entries do
    resource :applicants
  end

  namespace :company do
    resources :entries do
      resources :applicants, :only => ['index', 'show']
      get "mail_send" => 'applicants#mail_send'
    end
  end
  

  root 'launch_page#company'#'entries#index'

end

app/views/layouts/_header.html.erb
<% if company_signed_in? -%>
  <%= link_to image_tag("logo.png"), company_entries_path(current_company) %>
<% else -%>
  <%= link_to image_tag("logo.png"), root_path %>
<% end -%>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<p>
  <div Align="right">
    <% if company_signed_in? -%>
      <%= link_to "企業ログアウト", destroy_company_session_path, :method => :delete %>
    <% else -%>
      <% unless user_signed_in? -%>
	<%= link_to "企業の方　ログイン ", new_company_session_path %>
      <% end -%>

    <% end -%>
  </div>
</p>
<p>
  <div Align="center">
    <% if user_signed_in? -%>
      <%= link_to "ユーザーログアウト", destroy_user_session_path, :method => :delete %>
    <% else -%>
      <% unless company_signed_in? -%>
	<%= link_to "sign in with facebook ", user_omniauth_authorize_path(:facebook) %>

      <% end -%>
    <% end -%>





  </div>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Studyinturn2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body id="main">
  <div id="main_area">

    <%= yield %>    
  </div>
</body>
</html>